### inputs
*.txt
/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/Summary_files/Transcripts_percell_O2_percell_Genus_stats_biogeochemical_master_no2017.csv
### outputs
*KO_transcripts_per_cell_10_SAG_GENs.csv

rerun on 2021-12-07 after correcting for salinity of media samples

In [1]:
import pandas as pd
from pandas import DataFrame
import os
import sys
import csv
from pathlib import Path
import seaborn as sns
sns.set()
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
plt.show()
from collections import defaultdict
import os.path as op
import glob

os.chdir('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/20210325_GoM_recluster_analysis/For_kai')
outdir=('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/20210325_GoM_recluster_analysis/For_kai/')
matplotlib.__version__

'3.3.3'

In [2]:
KO_transcripts=pd.read_csv('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/Summary_files/Transcripts_percell_O2_percell_Genus_stats_biogeochemical_master_no2017.csv',
                          index_col=[1,2])
#KO_transcripts=KO_transcripts.drop("Unnamed:0")
KO_transcripts

                          Unnamed: 0    K00003  K00005  K00007  K00009  \
genus           date
AAA164-E04      20181030           1       NaN     NaN     NaN     NaN
                20190402           2       NaN     NaN     NaN     NaN
                20190709           3       NaN     NaN     NaN     NaN
AAA536-G10      20181030           5  0.000000     NaN     NaN     NaN
                20190402           6  0.100714     NaN     NaN     NaN
...                              ...       ...     ...     ...     ...
Winogradskyella 20190402         658       NaN     NaN     NaN     NaN
                20190709         659       NaN     NaN     NaN     NaN
Yoonia          20181030         661       NaN     NaN     NaN     NaN
                20190402         662  0.040045     NaN     NaN     NaN
                20190709         663       NaN     NaN     NaN     NaN

                          K00010    K00012   K00013    K00014    K00015  ...  \
genus           date                                                     ...
AAA164-E04      20181030     NaN       NaN      NaN  0.000000       NaN  ...
                20190402     NaN  0.280539      NaN       NaN       NaN  ...
                20190709     NaN       NaN      NaN       NaN       NaN  ...
AAA536-G10      20181030     NaN  0.003993  0.03194       NaN       NaN  ...
                20190402     NaN  0.035969      NaN  0.043163       NaN  ...
...                          ...       ...      ...       ...       ...  ...
Winogradskyella 20190402     NaN  0.029308      NaN       NaN       NaN  ...
                20190709     NaN  0.066819      NaN       NaN       NaN  ...
Yoonia          20181030     NaN       NaN      NaN       NaN       NaN  ...
                20190402     NaN       NaN      NaN  0.024027  0.008009  ...
                20190709     NaN       NaN      NaN       NaN       NaN  ...

                          ChlWWug/L  PhaeoWWug/L  \
genus           date
AAA164-E04      20181030       1.74          NaN
                20190402       2.91         0.62
                20190709       3.06         0.97
AAA536-G10      20181030       1.74          NaN
                20190402       2.91         0.62
...                             ...          ...
Winogradskyella 20190402       2.91         0.62
                20190709       3.06         0.97
Yoonia          20181030       1.74          NaN
                20190402       2.91         0.62
                20190709       3.06         0.97

                                                          Comments  \
genus           date
AAA164-E04      20181030  special G2P collection- not at high tide
                20190402                            G2P collection
                20190709                            G2P collection
AAA536-G10      20181030  special G2P collection- not at high tide
                20190402                            G2P collection
...                                                            ...
Winogradskyella 20190402                            G2P collection
                20190709                            G2P collection
Yoonia          20181030  special G2P collection- not at high tide
                20190402                            G2P collection
                20190709                            G2P collection

                          Bulk O2 consumption (uM)  Total cells/ml  \
genus           date
AAA164-E04      20181030                       NaN             NaN
                20190402                       NaN             NaN
                20190709                       NaN             NaN
AAA536-G10      20181030                       NaN             NaN
                20190402                       NaN             NaN
...                                            ...             ...
Winogradskyella 20190402                       NaN             NaN
                20190709                       NaN             NaN
Yoonia          20181030                       NaN             NaN
                20190402                       NaN             NaN
                20190709                       NaN             NaN

                          RSG+ cells per ml  NO3+NO2 (um)  NO2 (um)  NH4 (um)  \
genus           date
AAA164-E04      20181030                NaN          5.61      0.28      1.05
                20190402                NaN          1.53      0.03      0.55
                20190709                NaN          0.59      0.04      1.79
AAA536-G10      20181030                NaN          5.61      0.28      1.05
                20190402                NaN          1.53      0.03      0.55
...                                     ...           ...       ...       ...
Winogradskyella 20190402                NaN          1.53      0.03      0.55
                20190709                NaN          0.59      0.04      1.79
Yoonia          20181030                NaN          5.61      0.28      1.05
                20190402                NaN          1.53      0.03      0.55
                20190709                NaN          0.59      0.04      1.79

                          PO4 (um)
genus           date
AAA164-E04      20181030      0.81
                20190402      0.36
                20190709      0.31
AAA536-G10      20181030      0.81
                20190402      0.36
...                            ...
Winogradskyella 20190402      0.36
                20190709      0.31
Yoonia          20181030      0.81
                20190402      0.36
                20190709      0.31

[498 rows x 4526 columns]

In [3]:
tax=['full_GTDBtk_classification']

classification=KO_transcripts.filter(tax)
classification

                                                 full_GTDBtk_classification
genus           date
AAA164-E04      20181030  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
                20190402  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
                20190709  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
AAA536-G10      20181030  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190402  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
...                                                                     ...
Winogradskyella 20190402  d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...
                20190709  d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...
Yoonia          20181030  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190402  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190709  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...

[498 rows x 1 columns]

In [4]:
with open('aminopeptidases.txt') as f:
    aminopeptidases = f.read().splitlines()
with open('beta-glucosidases.txt') as f:
    glucosidases = f.read().splitlines()
with open('phosphatases.txt') as f:
    phosphatases = f.read().splitlines()

#aminopeptidases=aminopeptidases.strip('')

glucosidases

['K01222', 'K01232']

In [5]:
#df[df['A'].str.contains("hello")]
#my_list = df.columns.values.tolist()
KO_names=KO_transcripts.columns.values.tolist()
KO_names

amino_names=[i for i in KO_names if i.startswith(tuple(aminopeptidases))]
amino_names
aminopeptidase_KO=KO_transcripts.filter(amino_names)

aminopeptidase_KO=aminopeptidase_KO.dropna(how='all')

aminopeptidase_KO=aminopeptidase_KO.merge(classification, on=['genus', 'date'], how='left')

aminopeptidase_KO.to_csv(outdir+'aminopeptidase_KOs_transcripts_per_cell_10_SAG_Genera.csv')
aminopeptidase_KO

                            K01256    K01262    K01265    K01278  K01301  \
genus           date
AAA164-E04      20181030  0.035240       NaN  0.140961       NaN     NaN
                20190402       NaN       NaN  0.280539       NaN     NaN
AAA536-G10      20181030  0.047911       NaN  0.019963       NaN     NaN
                20190402  0.151071  0.028775  0.028775       NaN     NaN
                20190709  0.090970       NaN       NaN       NaN     NaN
...                            ...       ...       ...       ...     ...
Vicingaceae     20190709       NaN       NaN  0.140928       NaN     NaN
Winogradskyella 20190402       NaN  0.000000  0.009769  0.009769     NaN
Yoonia          20181030       NaN       NaN  0.409995       NaN     NaN
                20190402  0.080090       NaN       NaN       NaN     NaN
                20190709  0.596923       NaN       NaN       NaN     NaN

                          K01372    K06889  K08676  K19689    K19701  \
genus           date
AAA164-E04      20181030     NaN       NaN     NaN     NaN       NaN
                20190402     NaN       NaN     NaN     NaN       NaN
AAA536-G10      20181030     NaN       NaN     NaN     NaN       NaN
                20190402     NaN       NaN     NaN     NaN       NaN
                20190709     NaN       NaN     NaN     NaN       NaN
...                          ...       ...     ...     ...       ...
Vicingaceae     20190709     NaN       NaN     NaN     NaN  0.035232
Winogradskyella 20190402     NaN       NaN     NaN     NaN  0.029308
Yoonia          20181030     NaN  0.136665     NaN     NaN       NaN
                20190402     NaN       NaN     NaN     NaN       NaN
                20190709     NaN       NaN     NaN     NaN       NaN

                                                 full_GTDBtk_classification
genus           date
AAA164-E04      20181030  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
                20190402  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
AAA536-G10      20181030  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190402  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190709  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
...                                                                     ...
Vicingaceae     20190709  d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...
Winogradskyella 20190402  d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...
Yoonia          20181030  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190402  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190709  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...

[356 rows x 11 columns]

In [6]:
gluco_names=[i for i in KO_names if i.startswith(tuple(glucosidases))]

glucosidases_KO=KO_transcripts.filter(gluco_names)
#glucosidases_KO=glucosidases_KO.dropna(how='all')
glucosidases_KO=glucosidases_KO.merge(classification, on=['genus', 'date'], how='left')

glucosidases_KO.to_csv(outdir+'beta_glucoside_KOs_transcripts_per_cell_10_SAG_Genera.csv')
glucosidases_KO

                                                 full_GTDBtk_classification
genus           date
AAA164-E04      20181030  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
                20190402  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
                20190709  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
AAA536-G10      20181030  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190402  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
...                                                                     ...
Winogradskyella 20190402  d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...
                20190709  d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...
Yoonia          20181030  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190402  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190709  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...

[504 rows x 1 columns]

In [7]:
phospho_names=[i for i in KO_names if i.startswith(tuple(phosphatases))]

phospho_KO=KO_transcripts.filter(phospho_names)
phospho_KO=phospho_KO.dropna(how='all')
phospho_KO=phospho_KO.merge(classification, on=['genus', 'date'], how='left')


phospho_KO.to_csv(outdir+'phosphatase_KOs_transcripts_per_cell_10_SAG_Genera.csv')
phospho_KO

                            K01079    K01091  K01104  K01512  K01834  K02566  \
genus           date
AAA164-E04      20181030       NaN       NaN     NaN     NaN     NaN     NaN
                20190709       NaN       NaN     NaN     NaN     NaN     NaN
AAA536-G10      20181030       NaN  0.015970     NaN     NaN     NaN     NaN
                20190402  0.007194  0.028775     NaN     NaN     NaN     NaN
                20190709  0.040431  0.050539     NaN     NaN     NaN     NaN
...                            ...       ...     ...     ...     ...     ...
Vicingaceae     20190402       NaN       NaN     NaN     NaN     NaN     NaN
Winogradskyella 20190402  0.009769       NaN     NaN     NaN     NaN     NaN
                20190709  0.033410       NaN     NaN     NaN     NaN     NaN
Yoonia          20181030  0.136665       NaN     NaN     NaN     NaN     NaN
                20190402       NaN       NaN     NaN     NaN     NaN     NaN

                            K03273  K03651  K06117  K07025  K07313    K09769  \
genus           date
AAA164-E04      20181030  0.000000  0.0000     NaN     NaN     NaN       NaN
                20190709       NaN  0.4177     NaN     NaN     NaN       NaN
AAA536-G10      20181030       NaN     NaN     NaN     NaN     NaN  0.027948
                20190402  0.014388     NaN     NaN     NaN     NaN  0.050357
                20190709       NaN     NaN     NaN     NaN     NaN  0.040431
...                            ...     ...     ...     ...     ...       ...
Vicingaceae     20190402  0.043467     NaN     NaN     NaN     NaN       NaN
Winogradskyella 20190402       NaN     NaN     NaN     NaN     NaN       NaN
                20190709       NaN     NaN     NaN     NaN     NaN       NaN
Yoonia          20181030       NaN     NaN     NaN     NaN     NaN       NaN
                20190402       NaN     NaN     NaN     NaN     NaN  0.008009

                          K09880  K11777  K15634  K20074  K22305    K22390  \
genus           date
AAA164-E04      20181030     NaN     NaN     NaN     NaN     NaN  0.000000
                20190709     NaN     NaN     NaN     NaN     NaN       NaN
AAA536-G10      20181030     NaN     NaN     NaN     NaN     NaN       NaN
                20190402     NaN     NaN     NaN     NaN     NaN       NaN
                20190709     NaN     NaN     NaN     NaN     NaN       NaN
...                          ...     ...     ...     ...     ...       ...
Vicingaceae     20190402     NaN     NaN     NaN     NaN     NaN       NaN
Winogradskyella 20190402     NaN     NaN     NaN     NaN     NaN       NaN
                20190709     NaN     NaN     NaN     NaN     NaN  0.016705
Yoonia          20181030     NaN     NaN     NaN     NaN     NaN       NaN
                20190402     NaN     NaN     NaN     NaN     NaN       NaN

                                                 full_GTDBtk_classification
genus           date
AAA164-E04      20181030  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
                20190709  d__Bacteria;p__Verrucomicrobiota;c__Verrucomic...
AAA536-G10      20181030  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190402  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190709  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
...                                                                     ...
Vicingaceae     20190402  d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...
Winogradskyella 20190402  d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...
                20190709  d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__...
Yoonia          20181030  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...
                20190402  d__Bacteria;p__Proteobacteria;c__Alphaproteoba...

[226 rows x 19 columns]