In [1]:
import pandas as pd
from pandas import DataFrame
import os
import sys
import csv
from pathlib import Path
import seaborn as sns
sns.set()
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
plt.show()
from collections import defaultdict
import os.path as op
import glob

# input folder
os.chdir('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/20210325_GoM_recluster_analysis/gtdb')

# folder to save output files will create it if it does not exist
outdir="/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/20210325_GoM_recluster_images/csv_files_for_figures/"
if os.path.isdir(outdir):
    print(outdir, "already exists.")
else:
    os.mkdir(outdir)
    print(outdir, "is created.")

matplotlib.__version__

/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/20210325_GoM_recluster_images/csv_files_for_figures/ already exists.

'3.3.3'

rerun on 2021-12-07 after correcting for salinity of media samples

## Figure 2 csv files to create

Upload the color key file

1. abundance of all genera
2. O2 consumption of all SAGs labeled with RSG as well as their genus
3. Total O2 consumption /ml for all genera

In [2]:
with open("/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/Summary_files/Genera_with_5+SAGs.txt", "r") as tf:
    five_SAG = tf.read().split('\n')
print(five_SAG)

['Pelagibacter', 'SW10', 'SCGC-AAA076-P13', 'D2472', 'Amylibacter', 'Planktomarina', 'Akkermansiaceae', 'MAG-121220-bin8', 'MS024-2A', 'HTCC2207', 'Thioglobus', 'TMED189', 'Polaribacter', 'UBA10364', 'Puniceispirillum', 'UBA7428', 'AAA536-G10', 'MAG-120531', 'BACL14', 'SCGC-AAA160-P02', 'HC6-5', 'Pelagibacter_A', 'Hel1-33-131', 'OM182', 'AAA164-E04', 'Luminiphilus', 'MED-G11', 'UBA4582', 'UBA9926', 'Nitrosopumilus', 'SGZJ01', 'Synechococcus_C', 'Mariniblastus', 'MGIIb-O2', 'UBA952', 'ASP10-02a', 'MB11C04', 'MGIIa-L1', 'Octadecabacter', 'UBA9320', 'LFER01', 'Rubripirellula', 'Thioglobus_A', 'UBA4465', 'UBA4466', 'UBA7434', 'Litoricola', 'Marinisoma', 'Marinisoma', 'UBA1994', 'AG-337-I02', 'AG-422-B15', 'DEV007', 'GCA-002733185', 'HIMB59', 'Pontimonas', 'Aquiluna', 'Ascidiaceihabitans', 'IMCC9063', 'GCA-2707915', 'MED-G78', 'RS62', 'SYDM01', 'Synechococcus_E', 'Algibacter_B', 'Flavobacteriaceae', 'Flavobacteriales', 'GCA-2705205', 'MED-G09', 'UBA4421', 'CPC320', 'Hellea', 'SHAN690', 'UA16', 'UBA3537', 'UBA4441', 'Winogradskyella', 'Saprospiraceae', 'UBA4592', 'Arctic95D-9', 'EC70', 'Pirellulaceae', 'UBA1268', 'UBA3031', 'UBA4588', 'UBA9145', 'GCA-2683775', 'GCA-2705445', 'GCA-2862085', 'MED-G20', 'Porticoccus', 'TMED80', 'UBA2040', 'UBA5951', 'UBA6770', 'UBA7326', 'Yoonia', 'GCA-2698665', 'Planctomycetaceae', 'Poseidonia', 'TMED170', 'TMED25', 'UBA10347', 'UBA2970', 'UBA868', 'UBA8752', 'Verrucomicrobiales']

In [3]:
# abundance per day and weighted average
a_df=pd.read_csv('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/Summary_files/avg_O2_consumption_and_abundance_per_day_melt.csv',
                index_col=0)
#a_df=a_df[a_df['genus'].isin(five_SAG)]
print(a_df['genus'].nunique())
a_df

167

                  genus      date  cells_per_ml  avg_fmol_O2_consumed
0            AAA164-E04  20181030   1916.455808              0.002050
1            AAA536-G10  20181030  16915.541760              0.003056
2            AG-337-I02  20181030   9857.221878              0.009284
3            AG-414-E02  20181030    438.765267              0.002050
4            AG-422-B15  20181030   3313.158567              0.002050
..                  ...       ...           ...                   ...
499  Verrucomicrobiales  20190709    280.890811              0.001999
500              Vibrio  20190709    964.925624              0.001999
501         Vicingaceae  20190709   5084.185705              0.001999
502     Winogradskyella  20190709  10722.976925              0.001999
503              Yoonia  20190709   1200.327560              0.001999

[501 rows x 4 columns]

In [4]:
#Parse df down to just the genera with at least 5 SAGs

abundance_df=a_df[['genus', 'date', 'cells_per_ml']].copy()
abundance_df.to_csv(outdir+'Fig2_abundance.csv')

In [5]:
# CSV for boxplot 
cols=['name', 'Predicted_respiration_rate_fmol_O2perhr', 'GTDB_classification', 'gate', 'FACS_date']
SAGs=pd.read_csv('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/Summary_files/All_GoM_SAGs_1cell_20kb_decon_531normalized_predresp_rate_GTDBclass.csv',
                usecols=cols)

# per cell respiration rates
SAGs=SAGs[SAGs['gate']=='Respiring cells (RSG-positive)']
dates=[181030, 190402, 190709]
SAGs=SAGs[SAGs['FACS_date'].isin(dates)]
#SAGs=SAGs[SAGs['GTDB_classification'].isin(five_SAG)]
SAGs.to_csv(outdir+'per_cell_O2_consumption_rates_for_fiveSAG_genera.csv')

#average_weighted_O2 conusmption rates per genus
avg_weighted_df=a_df[['genus', 'date', 'avg_fmol_O2_consumed']]
avg_weighted_df.to_csv(outdir+'average_weighted_O2_consumption_per_cell.csv')
SAGs

,name,FACS_date,gate,Predicted_respiration_rate_fmol_O2perhr,GTDB_classification
1964,AH-545-A01,181030,Respiring cells (RSG-positive),0.004897,HIMB59
1965,AH-545-A02,181030,Respiring cells (RSG-positive),0.045645,UBA5951
1966,AH-545-A03,181030,Respiring cells (RSG-positive),0.014962,Unclassified
1967,AH-545-A04,181030,Respiring cells (RSG-positive),0.004827,Thioglobus_A
1968,AH-545-A05,181030,Respiring cells (RSG-positive),0.003989,Thioglobus
...,...,...,...,...,...
4728,AH-700-P10,190709,Respiring cells (RSG-positive),0.068309,Planktomarina
4729,AH-700-P11,190709,Respiring cells (RSG-positive),0.003930,Luminiphilus
4730,AH-700-P13,190709,Respiring cells (RSG-positive),0.029714,Planktomarina
4731,AH-700-P14,190709,Respiring cells (RSG-positive),0.007228,UBA8649
4732,AH-700-P18,190709,Respiring cells (RSG-positive),0.003867,Thioglobus

In [6]:
# total O2 conusmption per genus.
a_df['Total_O2_consumption']=a_df['cells_per_ml']*a_df['avg_fmol_O2_consumed']
perml_O2=a_df[['genus', 'date', 'Total_O2_consumption']]
perml_O2.to_csv(outdir+'total_O2_consumption_per_ml_per_genus.csv')

## Figure 3 csv files to create

A. cell diameter (volume) versus rRNA
B. cell diameter (volume) versus mRNA
C. PCA of Alpha
D. PCA of Bacterio
E. Genus Respiration v rRNA with size reflecting rhodopsin color by the color key above.
F. violin plots of Rhodopsin per um^3 of biomass split by Respiration levels 
    I need to figure out how to calculate biovolume per cell.

In [7]:
cols=['GTDB_genus', 'median_estimated_diameter']
genus=pd.read_csv('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/Summary_files/Supplemental_table_genus_statistics_light_metabolism.csv',
                 usecols=cols)
genus=genus.rename(columns={'GTDB_genus':'genus'})
genus

               genus  median_estimated_diameter
0       Pelagibacter                      0.300
1               SW10                      0.895
2    SCGC-AAA076-P13                      0.315
3              D2472                      0.360
4        Amylibacter                      0.540
..               ...                        ...
298           UBA974                      0.520
299            UBP15                      1.930
300           Vibrio                      1.180
301           ZODW24                      0.710
302     Unclassified                      0.660

[303 rows x 2 columns]

In [8]:
cols=['genus', 'date', 'mRNA_transcripts_per_cell', '16S_copies_per_cell', 'Weighted_avg_O2_consumed_per_cell']
RNA=pd.read_csv('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/20210325_GoM_recluster_images/rRNA/rRNA_O2_transcripts_stats_all_genera_no2017.csv', 
                index_col=0, usecols=cols)

cols=['proteorhodopsin_transcripts_per_cell', 'genus', 'date']
rhod=pd.read_csv('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/20210325_GoM_recluster_images/rRNA/rRNA_O2_transcripts_stats_all_genera.csv', 
                 usecols=cols)


RNA=RNA.merge(genus, on='genus', how='left')
RNA=RNA.merge(rhod, on=['genus', 'date'], how='left')
RNA=RNA[RNA['genus'].isin(five_SAG)]
RNA

,genus,date,mRNA_transcripts_per_cell,Weighted_avg_O2_consumed_per_cell,16S_copies_per_cell,median_estimated_diameter,proteorhodopsin_transcripts_per_cell
0,AAA164-E04,20181030,41.407165,0.002050,981.667559,1.06,NaN
1,AAA164-E04,20190402,71.256898,0.002101,39.275440,1.06,NaN
2,AAA164-E04,20190709,61.819633,0.001999,140.764254,1.06,NaN
3,AAA536-G10,20181030,55.388667,0.003056,737.519266,0.55,0.339367
4,AAA536-G10,20190402,96.361622,0.004028,1177.827026,0.55,1.697749
...,...,...,...,...,...,...,...
537,Winogradskyella,20190402,13.022716,0.002101,2.422830,0.89,0.205159
538,Winogradskyella,20190709,16.120198,0.001999,15.518743,0.89,0.083524
539,Yoonia,20181030,75.439063,0.002050,NaN,0.86,NaN
540,Yoonia,20190402,34.390677,0.002101,NaN,0.86,NaN
541,Yoonia,20190709,59.692345,0.001999,NaN,0.86,NaN

In [9]:
mRNA=RNA[['genus', 'date', 'mRNA_transcripts_per_cell', 'median_estimated_diameter']].copy()
mRNA=mRNA.dropna(how='any')
mRNA.to_csv(outdir+'Fig3_mRNA_diameter.csv')
mRNA

,genus,date,mRNA_transcripts_per_cell,median_estimated_diameter
0,AAA164-E04,20181030,41.407165,1.06
1,AAA164-E04,20190402,71.256898,1.06
2,AAA164-E04,20190709,61.819633,1.06
3,AAA536-G10,20181030,55.388667,0.55
4,AAA536-G10,20190402,96.361622,0.55
...,...,...,...,...
537,Winogradskyella,20190402,13.022716,0.89
538,Winogradskyella,20190709,16.120198,0.89
539,Yoonia,20181030,75.439063,0.86
540,Yoonia,20190402,34.390677,0.86
541,Yoonia,20190709,59.692345,0.86

In [10]:
O2mRNA=RNA[['genus', 'date', 'mRNA_transcripts_per_cell', 'median_estimated_diameter', 'Weighted_avg_O2_consumed_per_cell']].copy()
O2mRNA=O2mRNA.dropna(how='any')
O2mRNA=O2mRNA[O2mRNA['Weighted_avg_O2_consumed_per_cell']>0.0025]
O2mRNA.to_csv(outdir+'Fig3_O2_genera_mRNA_diameter.csv')
O2mRNA

,genus,date,mRNA_transcripts_per_cell,median_estimated_diameter,Weighted_avg_O2_consumed_per_cell
3,AAA536-G10,20181030,55.388667,0.550,0.003056
4,AAA536-G10,20190402,96.361622,0.550,0.004028
6,AG-337-I02,20181030,55.112989,0.405,0.009284
13,AG-422-B15,20190402,25.458490,0.300,0.003248
16,ASP10-02a,20190402,76.948725,0.545,1.023917
...,...,...,...,...,...
494,UBA7428,20181030,23.536468,0.470,0.009077
495,UBA7428,20190402,20.731195,0.470,0.064803
496,UBA7428,20190709,14.638116,0.470,0.005393
520,UBA9320,20190709,22.575790,0.520,0.004125
526,UBA9926,20190709,60.686329,0.780,0.005047

In [11]:
rRNA=RNA[['genus', 'date', '16S_copies_per_cell', 'median_estimated_diameter']].copy()
rRNA=rRNA.dropna(how='any')
rRNA.to_csv(outdir+'Fig3_rRNA_diameter.csv')
rRNA

               genus      date  16S_copies_per_cell  median_estimated_diameter
0         AAA164-E04  20181030           981.667559                       1.06
1         AAA164-E04  20190402            39.275440                       1.06
2         AAA164-E04  20190709           140.764254                       1.06
3         AAA536-G10  20181030           737.519266                       0.55
4         AAA536-G10  20190402          1177.827026                       0.55
..               ...       ...                  ...                        ...
525          UBA9926  20190402          1944.103387                       0.78
526          UBA9926  20190709          1221.920368                       0.78
536  Winogradskyella  20181030            39.079462                       0.89
537  Winogradskyella  20190402             2.422830                       0.89
538  Winogradskyella  20190709            15.518743                       0.89

[323 rows x 4 columns]

In [12]:
O2rRNA=RNA[['genus', 'date', '16S_copies_per_cell', 'median_estimated_diameter', 'Weighted_avg_O2_consumed_per_cell']].copy()
O2rRNA=O2rRNA.dropna(how='any')
O2rRNA=O2rRNA[O2rRNA['Weighted_avg_O2_consumed_per_cell']>0.0025]
O2rRNA.to_csv(outdir+'Fig3_O2_genera_rRNA_diameter.csv')
O2rRNA

,genus,date,16S_copies_per_cell,median_estimated_diameter,Weighted_avg_O2_consumed_per_cell
3,AAA536-G10,20181030,737.519266,0.550,0.003056
4,AAA536-G10,20190402,1177.827026,0.550,0.004028
6,AG-337-I02,20181030,523.029913,0.405,0.009284
13,AG-422-B15,20190402,158.246223,0.300,0.003248
16,ASP10-02a,20190402,1130.112708,0.545,1.023917
...,...,...,...,...,...
494,UBA7428,20181030,167.280366,0.470,0.009077
495,UBA7428,20190402,253.636433,0.470,0.064803
496,UBA7428,20190709,135.876092,0.470,0.005393
520,UBA9320,20190709,87.200558,0.520,0.004125
526,UBA9926,20190709,1221.920368,0.780,0.005047

In [13]:
Rhod=RNA[['genus', 'date', '16S_copies_per_cell', 'Weighted_avg_O2_consumed_per_cell', 'proteorhodopsin_transcripts_per_cell']].copy()
Rhod=Rhod.dropna(how='any')
Rhod.to_csv(outdir+'Fig3E_rRNA_O2_rhodhopsin.csv')
Rhod

,genus,date,16S_copies_per_cell,Weighted_avg_O2_consumed_per_cell,proteorhodopsin_transcripts_per_cell
3,AAA536-G10,20181030,737.519266,0.003056,0.339367
4,AAA536-G10,20190402,1177.827026,0.004028,1.697749
5,AAA536-G10,20190709,876.260279,0.001999,0.677222
6,AG-337-I02,20181030,523.029913,0.009284,0.274058
7,AG-337-I02,20190402,189.338832,0.002101,0.096356
...,...,...,...,...,...
525,UBA9926,20190402,1944.103387,0.002101,0.283614
526,UBA9926,20190709,1221.920368,0.005047,0.335184
536,Winogradskyella,20181030,39.079462,0.002050,0.236236
537,Winogradskyella,20190402,2.422830,0.002101,0.205159
538,Winogradskyella,20190709,15.518743,0.001999,0.083524

In [14]:
# FACS dot plots


cols=['name', 'Plate', 'Predicted_respiration_rate_fmol_O2perhr', 'GTDB_classification', 'gate', 'FACS_date', 'Sample_collection_Date', 'GTDBtk_classification']
SAGs=pd.read_csv('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/Summary_files/All_GoM_SAGs_1cell_20kb_decon_531normalized_predresp_rate_GTDBclass.csv',
                usecols=cols)

SAGs=SAGs[SAGs['FACS_date']==SAGs['Sample_collection_Date']]
SAGs=SAGs[SAGs['gate']=='Respiring cells (RSG-positive)']
SAGs[['domain', 'phyla', 'class', 'order', 'family', 'genus', 'species']]=SAGs.GTDBtk_classification.str.split(';', expand=True)

FACS_dot_plots=SAGs[['name', 'class', 'Plate']]

FACS_dot_plots['class']=FACS_dot_plots['class'].str[3:]

Classes=['Alphaproteobacteria', 'Gammaproteobacteria', 'Planctomycetes', 'Poseidoniia', 'Nitrososphaeria', 'Verrucomicrobiae', 'Acidimicrobiia',
         'Actinomycetia', 'Marinisomatia', 'Kapabacteria', 'Bacteroidia', 'Cyanobacteriia', 'UBA1135', 'Campylobacteria']

FACS_dot_plots['group']=np.where(FACS_dot_plots['class'].isin(Classes), FACS_dot_plots['class'], 'Other')
FACS_dot_plots

plates=FACS_dot_plots['Plate'].to_list()
plates=list(set(plates))
plates
for i in plates:
    df=FACS_dot_plots.loc[FACS_dot_plots['Plate'] == i ]
    df=df.drop(columns=['class', 'Plate'])
    i=str(i)
    df.to_csv(outdir+i+'_file_for_FACS_plot.csv', index=False)

df

/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/jacob_env/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/jacob_env/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

            name                group
1383  AH-269-A01  Gammaproteobacteria
1384  AH-269-A02                Other
1385  AH-269-A03                Other
1386  AH-269-A04          Bacteroidia
1387  AH-269-A05  Gammaproteobacteria
...          ...                  ...
1675  AH-269-P19  Gammaproteobacteria
1676  AH-269-P20  Alphaproteobacteria
1677  AH-269-P21          Bacteroidia
1678  AH-269-P22          Bacteroidia
1679  AH-269-P23  Alphaproteobacteria

[297 rows x 2 columns]

In [15]:
# FACS dot plots


cols=['name', 'Plate', 'Predicted_respiration_rate_fmol_O2perhr', 'GTDB_classification', 'gate', 'FACS_date', 'Sample_collection_Date', 'GTDBtk_classification']
SAGs=pd.read_csv('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/Summary_files/All_GoM_SAGs_1cell_20kb_decon_531normalized_predresp_rate_GTDBclass.csv',
                usecols=cols)

SAGs=SAGs[SAGs['FACS_date']==SAGs['Sample_collection_Date']]
SAGs=SAGs[SAGs['gate']=='Respiring cells (RSG-positive)']
SAGs[['domain', 'phyla', 'class', 'order', 'family', 'genus', 'species']]=SAGs.GTDBtk_classification.str.split(';', expand=True)

FACS_dot_plots=SAGs[['name', 'genus', 'Plate', 'order']]

FACS_dot_plots['genus']=FACS_dot_plots['genus'].str[3:]
FACS_dot_plots['order']=FACS_dot_plots['order'].str[3:]

Classes=['ASP10-02a', "Flavobacteriales"]

FACS_dot_plots['group']=np.where(FACS_dot_plots['genus'].isin(Classes), FACS_dot_plots['genus'],
                                 np.where(FACS_dot_plots['order'].isin(Classes), FACS_dot_plots['order'],'Other'))



plates=FACS_dot_plots['Plate'].to_list()
plates=list(set(plates))
plates
for i in plates:
    df=FACS_dot_plots.loc[FACS_dot_plots['Plate'] == i ]
    df=df.drop(columns=['genus', 'Plate', 'order'])
    i=str(i)
    df.to_csv(outdir+i+'_ASP10_file_for_FACS_plot.csv', index=False)

df

cats=FACS_dot_plots['group'].to_list()
cats=list(set(cats))
cats

/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/jacob_env/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/jacob_env/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/jacob_env/lib/python3.6/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

['Other', 'ASP10-02a', 'Flavobacteriales']

In [16]:
cols=['name', 'Plate', 'Predicted_respiration_rate_fmol_O2perhr', 'GTDB_classification', 'gate', 'FACS_date', 'Sample_collection_Date', 'GTDBtk_classification']
SAGs=pd.read_csv('/mnt/scgc/simon/microg2p/analyses/20210325_GoM_recluster/Summary_files/All_GoM_SAGs_1cell_20kb_decon_531normalized_predresp_rate_GTDBclass.csv',
                usecols=cols)

SAGs=SAGs[SAGs['FACS_date']==SAGs['Sample_collection_Date']]
SAGs=SAGs[SAGs['gate']=='All prokaryotes (SYTO-9-positive)']
SAGs[['domain', 'phyla', 'class', 'order', 'family', 'genus', 'species']]=SAGs.GTDBtk_classification.str.split(';', expand=True)

FACS_dot_plots=SAGs[['name', 'genus', 'Plate', 'order']]

FACS_dot_plots['genus']=FACS_dot_plots['genus'].str[3:]
FACS_dot_plots['order']=FACS_dot_plots['order'].str[3:]

Classes=['ASP10-02a', "Flavobacteriales"]

FACS_dot_plots['group']=np.where(FACS_dot_plots['genus'].isin(Classes), FACS_dot_plots['genus'],
                                 np.where(FACS_dot_plots['order'].isin(Classes), FACS_dot_plots['order'],'Other'))



plates=FACS_dot_plots['Plate'].to_list()
plates=list(set(plates))
plates
for i in plates:
    df=FACS_dot_plots.loc[FACS_dot_plots['Plate'] == i ]
    df=df.drop(columns=['genus', 'Plate', 'order'])
    i=str(i)
    df.to_csv(outdir+i+'_Syto9_SAGs_ASP10_file_for_FACS_plot.csv', index=False)

df

cats=FACS_dot_plots['group'].to_list()
cats=list(set(cats))
cats

/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/jacob_env/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/jacob_env/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/mnt/scgc/scgc_nfs/opt/common/anaconda3a/envs/jacob_env/lib/python3.6/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

['Other', 'ASP10-02a', 'Flavobacteriales']

In [32]:
vperc=pd.read_csv('/mnt/scgc/simon/microg2p/GoM_Viral_detection/Summary_files/All_days_virus_percentage.csv', index_col=0)
vperc['date']=vperc['date']+20000000

vO2=RNA[['genus', 'date', 'Weighted_avg_O2_consumed_per_cell']].copy()
vO2=vO2.drop_duplicates()
vperc=vperc.merge(vO2, on=['genus', 'date'], how='left')
vperc.to_csv(outdir+'All_days_avg_O2_consumption_and_abundance_virus_percentage.csv')
vperc

,genus,date,virus_identified_percentage,Weighted_avg_O2_consumed_per_cell
0,AAA536-G10,20181030,21.428571,0.003056
1,D2472,20181030,97.142857,0.003294
2,GCA-2707915,20181030,80.000000,0.002050
3,HTCC2207,20181030,14.285714,0.002050
4,LFER01,20181030,37.500000,NaN
5,Luminiphilus,20181030,69.230769,0.002050
6,MAG-121220-bin8,20181030,25.000000,0.011689
7,MS024-2A,20181030,84.615385,0.005978
8,Marinisoma,20181030,100.000000,0.004789
9,Nitrosopumilus,20181030,6.666667,0.003861
10,Pelagibacter,20181030,12.206573,0.003248
11,Planktomarina,20181030,25.000000,0.251576
12,Puniceispirillum,20181030,72.222222,0.005071
13,SCGC-AAA160-P02,20181030,60.000000,0.011975
14,SYDM01,20181030,100.000000,0.002050
15,TMED189,20181030,15.000000,0.003155
16,Thioglobus,20181030,7.142857,0.005393
17,Thioglobus_A,20181030,21.428571,0.002050
18,UBA4582,20181030,66.666667,0.002050
19,AAA536-G10,20190402,44.444444,0.004028
20,ASP10-02a,20190402,33.333333,1.023917
21,Amylibacter,20190402,15.625000,0.045158
22,BACL14,20190402,33.333333,0.002101
23,D2472,20190402,13.888889,0.004416
24,HC6-5,20190402,36.363636,0.042521
25,HTCC2207,20190402,41.176471,0.003283
26,MAG-120531,20190402,25.000000,0.009156
27,MAG-121220-bin8,20190402,23.076923,0.016772
28,Pelagibacter,20190402,14.444444,0.002526
29,Planktomarina,20190402,48.000000,0.302153
30,Polaribacter,20190402,7.142857,0.025400
31,SCGC-AAA076-P13,20190402,15.384615,0.004176
32,Thioglobus,20190402,9.090909,0.004662
33,UBA4582,20190402,55.555556,0.006502
34,UBA7428,20190402,30.000000,0.064803
35,Unclassified,20190402,21.186441,NaN
36,Winogradskyella,20190402,40.000000,0.002101
37,Amylibacter,20190709,44.444444,0.054759
38,HTCC2207,20190709,28.571429,0.003507
39,Hel1-33-131,20190709,35.714286,0.005266
40,MAG-121220-bin8,20190709,7.692308,0.003637
41,MS024-2A,20190709,22.222222,0.003255
42,Pelagibacter,20190709,10.185185,0.002272
43,Planktomarina,20190709,51.724138,0.103898
44,Puniceispirillum,20190709,36.363636,0.003888
45,SCGC-AAA076-P13,20190709,16.949153,0.004215
46,Thioglobus,20190709,12.500000,0.005608
47,UBA9926,20190709,60.000000,0.005047
48,Unclassified,20190709,25.641026,NaN

,index,genus,date,virus_identified_percentage,Weighted_avg_O2_consumed_per_cell
0,0,AAA536-G10,20181030,21.428571,0.003056
1,1,D2472,20181030,97.142857,0.003294
2,2,GCA-2707915,20181030,80.000000,0.002050
3,3,HTCC2207,20181030,14.285714,0.002050
4,4,LFER01,20181030,37.500000,NaN
5,5,Luminiphilus,20181030,69.230769,0.002050
6,6,MAG-121220-bin8,20181030,25.000000,0.011689
7,7,MS024-2A,20181030,84.615385,0.005978
8,8,Marinisoma,20181030,100.000000,0.004789
9,9,Nitrosopumilus,20181030,6.666667,0.003861
10,10,Pelagibacter,20181030,12.206573,0.003248
11,11,Planktomarina,20181030,25.000000,0.251576
12,12,Puniceispirillum,20181030,72.222222,0.005071
13,13,SCGC-AAA160-P02,20181030,60.000000,0.011975
14,14,SYDM01,20181030,100.000000,0.002050
15,15,TMED189,20181030,15.000000,0.003155
16,16,Thioglobus,20181030,7.142857,0.005393
17,17,Thioglobus_A,20181030,21.428571,0.002050
18,18,UBA4582,20181030,66.666667,0.002050
19,0,AAA536-G10,20190402,44.444444,0.004028